### ISSUE TITLE
trylock 里的 Count() 方法似乎有些问题

### ISSUE THREAD

**Issue by maolonglong** [smallnest/dive-to-gosync-workshop#3]
我不太确定，我理解的 39 行意思是如果有一个 goroutine 正占用着锁，count 需要加 1，但是 38 行已经把 `v` 变成了 WaiterCount，此时的 `(v & mutexLocked)` 似乎是个错误的语义。

https://github.com/smallnest/dive-to-gosync-workshop/blob/fa9fdc4e30e0fbf6d4cf5c0b63a07a9a486d302d/1.basic/mutex/trylock/main.go#L36-L41

**Comment by smallnest** [comment]
是的，赞细节，这里的确是个问题
