### ISSUE TITLE
关于极客时间中《Go 并发编程实战课》，提到的CyclicBarrier库好像有Bug

### ISSUE THREAD

**Issue by CoderIvan** [smallnest/dive-to-gosync-workshop#5]
想请教老师一个问题

关于https://github.com/marusama/cyclicbarrier/blob/master/cyclicbarrier.go#L119-L135

![image](https://user-images.githubusercontent.com/7960859/156562384-8df79581-4762-42e1-9f60-9c697a54971d.png)

b.round.count在高并发下是不是有可能大于parties的，并没有受到保护

我尝试在L135到L137之间增加了一点休眠时间，就好容易复现到这个Bug

**Comment by smallnest** [comment]
CyclicBarrier应用场景应该是每个party自己调用Await,不应该允许其他非parties的goroutine去调用Await。
基于这个使用场景，理论不会出现b.round.count大于parties的情况的。
如果不基于这个场景，那么就可能出现你说的问题，然后#138行会panic。

你是不是有其它goroutine调用了Await?

**Comment by CoderIvan** [comment]
我把cyclicbarrier的源码拷到本地并加了`time.Sleep`方便复现，代码如下：
![image](https://user-images.githubusercontent.com/7960859/156908651-0a2a3350-dbdb-4e08-8a40-60c2b411b0da.png)
```golang
package main

import (
	"context"
	"sync"

	"example.com/m/cyclicbarrier"
)

func main() {
	barrier := cyclicbarrier.New(2)
	wg := &sync.WaitGroup{}

	wg.Add(1)
	go func() {
		barrier.Await(context.Background())
		wg.Done()
	}()

	wg.Add(1)
	go func() {
		barrier.Await(context.Background())
		wg.Done()
	}()

	wg.Add(1)
	go func() {
		barrier.Await(context.Background())
		wg.Done()
	}()

	wg.Wait()
}
```

结果如下：
![image](https://user-images.githubusercontent.com/7960859/156908666-4fe78910-25e5-4151-8bfa-9cab92a5db71.png)

**Comment by smallnest** [comment]
这就对了，你parties设置2,使用了三个goroutine去awaot,所以会panic.

你应该使用和parties相同的goroutine去await
